### PR TITLE
add dot output to visualize a BDDFunc as diagram using graphviz, this…

### PR DESCRIPTION
**Pull request by mtttichy**
… comes handy in debugging boolean expressions

### CODE REVIEW

**Comment by cfallin** [comment]
Thanks! This is a really useful addition.

I made some minor tweaks in an additional commit, mostly formatting/style. I renamed the function from `export_bdd_to_dot()` to `to_dot()` as well. Otherwise, looks great -- merged.

**Comment by cfallin** [comment]
Published to crates.io as [version 0.3.2](https://crates.io/crates/boolean_expression/0.3.2).

**Comment by cfallin** [comment]
And, actually, I just realized that the node-subset collection did not avoid revisiting nodes. Now fixed and released as 0.3.3.

**Comment by mtttichy** [comment]
Thanks. Also your recursive collect is probably faster than mine. Which pretty printer did you use, so i can already do the right formatting?

**Comment by cfallin** [comment]
I used `rustfmt`, which can also be run over a whole crate with `cargo fmt` (which invokes the `cargo-fmt` command). I think that the default rustup distro should include it, but if not, `cargo install rustfmt` should work.

**Pull request merged**
